
services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: nestjs-postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nestjs_auth"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: