name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build the NestJS app
      - name: Build
        run: npm run build

      # Run lint
      - name: Lint
        run: npm run lint

      # Run tests
      - name: Run tests
        run: npm test
